---

- hosts: all
  become: true
  tasks:
  - name: install the apache2 and PHP packages
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
