# Minio deployment for single node/single disk operation


apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1  # This needs to remain 1 for single node operations
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /data
          envFrom:
          - secretRef:
              name: minio-secret
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
          - name: minio-data
            mountPath: /data
      - name: minio
        image: minio/minio
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address :9001
        envFrom:
        - secretRef:
            name: minio-secret
        ports:
        - containerPort: 9000  # minio api port
        - containerPort: 9001  # minio console port
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        nfs:
          server: 192.168.1.111   # tn.lan  TrueNas Mount
          path: /mnt/tank/nfs
          readOnly: false

