apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /data
          envFrom:
            - secretRef:
                name: minio-secret
          ports:
            - containerPort: 9000
            - containerPort: 9001  
          volumeMounts:
            - name: minio-data
              mountPath: /data
    volumes:
      - name: minio-data
        persistentVolumeClaim:
        claimName: minio-pvc
          #volumes:
          #- name: minio-data
          #nfs:
          #  server: 192.168.1.71
          #  path: /mnt/tank/nfs
          #  readOnly: false
  
