apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
<<<<<<< HEAD

=======
    storageClassN:ame: longhorn
>>>>>>> refs/remotes/origin/main
