apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  labels:
    app: minio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
    storageClassN:ame: longhorn
