apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /mnt/tank/pbs_vol1
    server: 192.168.1.111
