---
# Activate and mount the Borg Repo

- hosts: borg
  become: true

  tasks:

    - name: activate borg repo lambda_event
      community.general.lvol:
      vg: borgvg
      lv: borglv01
      active: true

    - name: Mount the borg repo lv
      ansible.builtin.shell: |
        mount /dev/mapper/borgvg-borglv01 /mnt/borg

---
# This playbook will run a BORG CREATE archive against all nodes in the cluster.

- hosts: all
  become: true
  serial: 1  # Run tasks one node at a time
  vars:
    borg_passphrase: "{{ borgrepopw }}"
    random_number: "{{ 1000 | random }}"

  tasks:

    - name: Bring in secrets
      include_vars: var_secret.yaml # Decrypt and process vars from the project var_secret.yaml

    - name:  Run the Borg Create Job
      ignore_errors: yes  # We do this due to how BORG reports skipped files
      ansible.builtin.shell: |
        borgbackup create --show-rc  --stats --exclude /proc --exclude /run --exclude /sys borg@192.168.1.55:/mnt/borg::{{ ansible_hostname }}-{{ random_number }} /
      environment:
        BORG_PASSPHRASE: "{{ borg_passphrase }}"

    - name: prune old archives
      ignore_errors: yes
      ansible.builtin.shell:  |
        borgbackup prune --keep-daily 7 --keep-weekly 4 --keep-monthly 3 -P {{ ansible_hostname }} borg@192.168.1.55:/mnt/borg
      environment:
        BORG_PASSPHRASE:  "{{ borg_passphrase }}"

---
# Activate and umount borg repo

- hosts: borg
  become: true

  tasks:

    - name: Umount the borg repo lv
      ansible.builtin.shell: |
        umount /mnt/borg

    - name: deactivate borg repo
      community.general.lvol:
      vg: borgvg
      lv: borglv01
      active: False
