---
# This playbook will run a BORG CREATE archive against all nodes in the cluster.

- hosts: backup
  become: true  #Run the jobs as 'root'
  serial: 1  # Run tasks one node at a time.  We need to do this because having two borg processes writting to the same repo is BAD!!!!
  vars:
#    borg_passphrase: "{{ borgrepopw }}"  We have this commented at this time because the repo in use is not encrypted
    random_number: "{{ 1000 | random }}"

  tasks:

    - name: Bring in secrets
      include_vars: var_secret.yaml # Decrypt and process vars from the project var_secret.yaml

    - name:  Run the Borg Create Job
      ignore_errors: yes  # We do this due to how BORG reports skipped files
      ansible.builtin.shell: |
        borgbackup create --show-rc  --stats --exclude /proc --exclude /run --exclude /sys borg@192.168.1.55:/home/borg/repo::{{ ansible_hostname }}-{{ random_number }} /
      environment:

        BORG_PASSPHRASE: "{{ borg_passphrase }}"

      register: results1

    - debug:
        var: results1

    - name: prune old archives
      ignore_errors: yes
      ansible.builtin.shell:  |
        borgbackup prune --keep-daily 7 --keep-weekly 4 --keep-monthly 3 --stats --list -P {{ ansible_hostname }} borg@192.168.1.55:/home/borg/repo
      environment:
        BORG_PASSPHRASE: "{{ borg_passphrase }}"

      register: results2

    - debug:
        var: results2


