---

- hosts: node3
  become: true
  tasks:

  - name: install the docker.io
    package:
      name:
        - docker.io
      state: latest
      update_cache: yes


  - name: Check the status of the service
    systemd:
      name: docker
      state: started

  - name: Create Portainer Volume
    docker_volume:
      name: Portainer_vol
      state: present

  - name: Install Portainer
    docker_container:
      detach: true
      image: portainer/portainer-ce:latest
      published_ports:
        - "9000:9000"
        - "8000:8000"
        - "9443:9443"
      name: Portainer
      volumes:
        -  "/var/run/docker.sock:/var/run/docker.sock"
        -  "Portainer_vol:/data"

  - name: install the docker-compose
    package:
      name:
        - docker-compose
      state: latest
      update_cache: yes
